{{- if eq .Values.secrets.provider "doppler" }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-doppler-token-{{ .Values.secrets.doppler.config }}

type: Opaque
stringData:
  serviceToken: {{ .Values.secrets.doppler.token }}
{{- end }}
