apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret

metadata:
  # Matches the managedSecret below
  name: {{ .Release.Name }}-doppler-secret
spec:
  # Where to find the Service Token
  tokenSecret:
    name: doppler-token-secret-{{ .Values.doppler.config }}
  # Which secret to create for the pods
  managedSecret:
    # Matches the metadata above and the deployment referencing it
    name: {{ .Release.Name }}-doppler-secret 
    type: Opaque
  project: {{ .Values.doppler.project }}
  config: {{ .Values.doppler.config }}
  resyncSeconds: 30 # Too frequent, delete after the test
