apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret-{{ .Values.doppler.config }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  serviceToken: {{ required "A valid .Values.doppler.token is required" .Values.doppler.token | b64enc }}
