apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-test-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  TEST_PLAIN_SECRET: {{ "this-is-plain-secret-value" | b64enc }}
