apiVersion: v2
name: postgres-cluster
description: CloudNative PostgreSQL cluster
version: 0.1.0
type: application
dependencies:
  - name: cloudnative-pg
    alias: operator
    version: ^0.x.x
    repository: https://cloudnative-pg.github.io/charts
