# Basic app configuration
app:
  name: n8n
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  revisionHistoryLimit: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  servicePort: 80
  containerPort: 5678
  monitors:
    enabled: true
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "5678"
      prometheus.io/path: "/metrics"
  # Security context for n8n container
  # n8n runs as the 'node' user (UID 1000) inside the container
  # fsGroup ensures the mounted volume has the correct group ownership
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Fallback: use init container if fsGroup doesn't work
  # Set to true if you're still getting permission errors
  useInitContainer: false

# Persistent storage configuration
persistence:
  enabled: true
  size: 10Gi
  storageClass: hcloud-volumes
  mountPath: /home/node/.n8n

# Ingress configuration
ingress:
  enabled: true
  className: traefik
  domain:
    base: cloud.appifyhub.local
    prefix: n8n
  tls:
    enabled: false
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.tls: "false"

# Secret management
secrets:
  provider: doppler
  doppler:
    token: "" # Service Token, to be set at install time
    project: n8n-cloud
    config: local

# Non-sensitive configuration
config:
  enabled: true
  values:
    # Timezone configuration
    GENERIC_TIMEZONE: "Europe/Berlin"
    TZ: "Europe/Berlin"
    # Database configuration (SQLite)
    # SQLite pool size for read connections - improves performance
    DB_SQLITE_POOL_SIZE: "10"
    # Security configuration
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
    N8N_RUNNERS_ENABLED: "true"
    # Block access to environment variables from Code Node (recommended for security)
    N8N_BLOCK_ENV_ACCESS_IN_NODE: "true"
    # Disable bare repositories in Git Node (security)
    N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"
    
    # Proxy configuration (required for Traefik ingress)
    # Tells n8n to trust the first proxy hop (Traefik) for X-Forwarded-For headers
    N8N_PROXY_HOPS: "1"
    
    # n8n configuration
    N8N_PORT: "5678"
    N8N_PROTOCOL: "http"
    N8N_HOST: "n8n.cloud.appifyhub.local"
    WEBHOOK_URL: "http://n8n.cloud.appifyhub.local/"
