{{- if eq .Values.secrets.provider "doppler" }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret

metadata:
  name: {{ .Release.Name }}-doppler-secret

spec:
  tokenSecret:
    name: {{ .Release.Name }}-doppler-token-{{ .Values.secrets.doppler.config }}
  managedSecret:
    name: {{ .Values.secrets.managedSecretName }}
    type: Opaque
  project: {{ .Values.secrets.doppler.project }}
  config: {{ .Values.secrets.doppler.config }}
  resyncSeconds: 300
{{- end }}
