{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Values.app.name }}
    instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
  {{- if .Values.config.values }}
  {{- toYaml .Values.config.values | nindent 2 }}
  {{- end }}
{{- end }}

