{{- if eq .Values.secrets.provider "doppler" }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret

metadata:
  # Matches the managedSecret below
  name: {{ .Release.Name }}-doppler-secret

spec:
  # Where to find the Service Token
  tokenSecret:
    name: {{ .Release.Name }}-doppler-token-{{ .Values.secrets.doppler.config }}
  # Which secret to create for the pods
  managedSecret:
    # Matches the metadata above and the deployment referencing it
    name: {{ .Release.Name }}-doppler-secret
    type: Opaque
  project: {{ .Values.secrets.doppler.project }}
  config: {{ .Values.secrets.doppler.config }}
  resyncSeconds: 300 # 5 minutes
{{- end }}

