{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ .Values.app.name }}
    instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
