{{- if .Values.s3Credentials.admin.accessKey }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.seaweedfs.s3.existingConfigSecret }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: {{ .Release.Name }}

type: Opaque
stringData:
  seaweedfs_s3_config: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": {{ .Values.s3Credentials.admin.accessKey | quote }},
              "secretKey": {{ .Values.s3Credentials.admin.secretKey | quote }}
            }
          ],
          "actions": ["Admin", "Read", "Write", "List", "Tagging"]
        }
        {{- if .Values.s3Credentials.readOnly.accessKey }},
        {
          "name": "readonly",
          "credentials": [
            {
              "accessKey": {{ .Values.s3Credentials.readOnly.accessKey | quote }},
              "secretKey": {{ .Values.s3Credentials.readOnly.secretKey | quote }}
            }
          ],
          "actions": ["Read", "List"]
        }
        {{- end }}
      ]
    }
{{- end }}
