apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPorts.http }}
  selector:
    app: echo
