apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-postgres-test
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "{{ .Values.postgresql.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.postgresql.storageSize }}"
