{{- if eq .Values.secrets.provider "doppler" }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-doppler-token-{{ .Values.secrets.doppler.config }}

type: Opaque
data:
  serviceToken: {{ required "A valid .Values.secrets.doppler.token is required" .Values.secrets.doppler.token | b64enc }}
{{- end }}
